### PR TITLE
Added windows logo

### PR DESCRIPTION
**Pull request by SSHSRN**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

### CODE REVIEW

**Comment by SSHSRN** [comment]
fixes #80

**Comment by SSHSRN** [comment]
@neelshah2409 Kindly check!

**Comment by nik132-eng** [comment]
Microsoft logo is already there

**Comment by SSHSRN** [comment]
> Microsoft logo is already there

Well, it is not the case.

You have drawn the windows 10 logo and named it as microsoft logo.

image

This is the actual microsoft logo and I have also updated the same by drawing the logo using turtle.
@neelshah2409 Kindly check!

**Pull request merged**
