### PR TITLE
Added mandala design python file using turtle

### PR DESCRIPTION
**Pull request by Aniket-508**
Solves #2

### CODE REVIEW

**Comment by Aniket-508** [comment]
@neelshah2409 Please have a look !

**Comment by neelshah2409** [comment]
> @neelshah2409 Please have a look !

Please add some description of it and also screenshot of output.

**Comment by Aniket-508** [comment]
Description - 
It forms vivid designs through overalpping circles of different sizes and colors

Screenshot of output -

**Comment by neelshah2409** [comment]
> @neelshah2409 Is that ok?

Amazing work 🎊, hoping for the same through out the program.

**Pull request merged**
