### PR TITLE
Python code to draw Indian Tricolor Flag using the turtle module

### PR DESCRIPTION
**Pull request by Godzilla5111**
Making an Indian Flag :-

The process can be divided into 4 steps:

We draw
1. The rectangle with orange color
2. Then the middle rectangle
3. Then the last Green Rectangle
4. Then Ashoka Chakra inside the middle rectangle

#2

### CODE REVIEW

**Comment by Godzilla5111** [comment]
@neelshah2409 Completed the flag. Please review and merge it.

**Comment by neelshah2409** [comment]
> @neelshah2409 Completed the flag. Please review and merge it.

Please attach the ss of output here.

**Comment by Godzilla5111** [comment]
Hope this works @neelshah2409 !

**Comment by neelshah2409** [comment]
> Hope this works @neelshah2409 !

Good work 👏, hoping for the same through out the program.

**Pull request merged**
